package com.noki.util;

import java.util.ArrayList;

public class HanziData6 {

  static ArrayList hl = new ArrayList();
  static {
    Object[] rec = new Object[2];
    rec = new Object[2];
    rec[0] = new String("ïÚ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïÛ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïÜ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïÝ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïÞ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾µ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïá");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïß");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïà");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïâ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïã");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÁÍ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïä");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïå");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïæ");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïç");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïè");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïé");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïê");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïë");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïì");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÀØ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïí");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Á­");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïî");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïï");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïð");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ïâ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³¤");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÃÅ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÅ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÉÁ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÆ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±Õ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÎÊ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("´³");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Èò");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÇ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÏÐ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÈ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼ä");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÉ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÊ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÃÆ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ¢");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÄÖ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹ë");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÎÅ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãË");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ãö");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÌ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·§");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸ó");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ºÒ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÍ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÎ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÔÄ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÏ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÐ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÑË");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÑ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÒ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÓ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÔ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÑÖ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÕ");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("²û");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À»");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÖ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À«");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ã×");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãØ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÙ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÚ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÛ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸·");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶Ó");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úä");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úã");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úæ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Èî");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úå");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·À");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñô");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Òõ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õó");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("½×");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("×è");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úè");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úç");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("°¢");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÍÓ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úé");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸½");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼Ê");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â½");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â¤");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³Â");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úê");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âª");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ä°");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("½µ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÏÞ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úë");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÉÂ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±Ý");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úì");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶¸");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ôº");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³ý");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úí");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÔÉ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÏÕ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Åã");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úî");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úï");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úð");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Áê");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÌÕ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÏÝ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Óç");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â¡");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úñ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ëå");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ëå");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úò");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ëæ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Òþ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸ô");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úó");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úó");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("°¯");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ï¶");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÕÏ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ëí");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Úô");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÄ");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ãÄ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Á¥");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Á¥");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¿");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¿");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¿");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÀ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÁ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÄÑ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("È¸");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñã");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÐÛ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÑÅ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼¯");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹Í");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ïô");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("´Æ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Óº");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÂ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³û");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÃ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µñ");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÅ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Óê");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö§");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñ©");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö©");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¨");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Áã");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À×");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±¢");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Îí");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ðè");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö«");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ïö");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öª");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õð");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¬");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ã¹");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("»ô");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö®");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö­");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÄÞ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÁØ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ëª");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ï¼");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¯");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö°");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö±");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â¶");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("°Ô");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Åù");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö²");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Çà");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¦");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾¸");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾²");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µå");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ç");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¿¿");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÃÒ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ãæ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ØÌ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸ï");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("½ù");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñ¥");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("°Ð");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷°");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷±");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ð¬");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("°°");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷²");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷³");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷´");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÇÊ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÇÊ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾Ï");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷·");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¶");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±Þ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷µ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¸");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¹");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Î¤");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÈÍ");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º«");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("è¸");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("è¹");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("è¹");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("èº");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾Â");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Òô");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÔÏ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÉØ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ò³");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶¥");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Çê");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ñü");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ïî");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ë³");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ðë");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("çï");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Íç");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹Ë");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶Ù");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ñý");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("°ä");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ËÌ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ñþ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ô¤");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â­");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Áì");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÆÄ");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾±");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾±");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¡");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¡");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼Õ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¢");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¢");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò£");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¤");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÒÃ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Æµ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Æµ");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÍÇ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¥");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ó±");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¿Å");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ìâ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¦");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò§");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÑÕ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶î");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¨");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò©");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µß");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("òª");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò«");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("²ü");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("²ü");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò¬");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ò­");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("È§");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ç");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ì©");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ìª");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ì«");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ì¬");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Æ®");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ì­");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ì®");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·É");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ê³");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("â¸");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ï");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ð");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("²Í");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ñ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ó");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ò");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼¢");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("â¼");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("â½");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("â¾");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("â¿");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÀ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÁ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¹");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Òû");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("½¤");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÊÎ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±¥");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ËÇ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÂ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶ü");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÈÄ");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÃ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("½È");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±ý");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÄ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶ö");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÅ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÄÙ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÆ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÏÚ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹Ý");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÇ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À¡");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÈ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("²ö");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÉ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Áó");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÊ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âË");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âø");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÌ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÍ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("âÎ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ê×");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ø¸");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ùå");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ïã");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¥");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ü°");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âí");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ô¦");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÍÔ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñ±");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³Û");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Çý");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("²µ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â¿");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æà");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ê»");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æá");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æâ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾Ô");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æã");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("×¤");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÍÕ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æå");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼Ý");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æä");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ææ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æç");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âî");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("½¾");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æè");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âæ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º§");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æé");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æê");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³Ò");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñé");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¿¥");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æë");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Æï");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æì");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æí");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æî");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Æ­");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æï");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("É§");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æð");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æñ");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æò");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("å¹");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æó");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æô");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æô");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ââ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æõ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æö");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Öè");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æ÷");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æø");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹Ç");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷»");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷º");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¾");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¼");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º¡");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¿");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷À");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Â");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Á");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ä");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ã");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Å");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Æ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ç");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ëè");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸ß");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ô");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Õ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ö");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ø");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ú");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷×");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Û");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ù");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("××");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ü");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ý");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Þ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ß");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷à");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÛË");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Øª");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("å÷");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹í");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¿ý");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("»ê");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷É");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÆÇ");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷È");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ê");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ì");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Ë");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Í");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Îº");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷Î");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ä§");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Óã");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÏ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â³");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÐ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÑ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÒ");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÓ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÔ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÖ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±«");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö×");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öØ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÙ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÙ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÚ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÛ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÜ");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÝ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öÞ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÏÊ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öß");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öà");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öá");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öâ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öã");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öä");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Àð");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öå");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öæ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öç");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öè");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öé");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öê");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öë");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öì");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öí");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öî");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öï");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öð");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öñ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öò");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öó");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öô");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾¨");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öõ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öö");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö÷");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öø");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Èú");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Èú");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öù");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öú");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öû");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öü");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öý");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öþ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¡");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¢");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷£");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¤");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¥");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¦");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷§");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¨");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±î");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷©");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ª");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷«");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¬");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¬");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷­");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÁÛ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷®");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷¯");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Äñ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¯");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¼¦");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð°");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ãù");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Å¸");
    rec[1] = new String("o");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñ»");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð±");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð²");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð³");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð´");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðµ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñ¼");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ñì");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð·");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¶");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ô§");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÍÒ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¸");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðº");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¹");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð»");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¼");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¸ë");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð½");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ºè");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¾");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¿");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¾é");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÀ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶ì");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÁ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÂ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÃ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÄ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Èµ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÅ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÆ");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÇ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Åô");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÈ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÉ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÊ");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷½");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðË");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÌ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÍ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÎ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÏ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º×");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÐ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÑ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÒ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÓ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÔ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÕ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÖ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðØ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ó¥");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð×");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ðÙ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("õº");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â¹");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ä");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷å");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷å");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷æ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ç");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷è");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â´");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ê");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ë");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âó");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ôð");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ôï");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âé");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷á");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷â");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("»Æ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ùä");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Êò");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Àè");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ð¤");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ºÚ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ç­");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ä¬");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ì");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷í");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷î");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ð");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ï");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ñ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ô");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ó");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ò");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷õ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ö");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("íé");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("íê");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("íë");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¼");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö½");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¾");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¶¦");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ø¾");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹Ä");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ø»");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ü±");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Êó");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷÷");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ø");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ù");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷û");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ú");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±Ç");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ü");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ý");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷þ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Æë");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ì´");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("³Ý");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö³");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö´");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Áä");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öµ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¶");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö·");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¸");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¸");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö¹");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("öº");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("È£");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ö»");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Áú");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹¨");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("íè");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹ê");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹ê");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¹ê");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ùß");
    rec[1] = new String("y");
    hl.add(rec);

  }

  /**
   * @param args
   */
  public static void main(String[] args) {
    // TODO Auto-generated method stub

  }

}
