package com.noki.util;

import java.util.ArrayList;

public class HanziData2 {
  static ArrayList hl = new ArrayList();
  static {

    Object[] rec = new Object[2];
    rec = new Object[2];
    rec[0] = new String("œ¸");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º“");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â∑");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("»›");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("øÌ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±ˆ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Àﬁ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Àﬁ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º≈");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ºƒ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“˙");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√‹");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ø‹");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∏ª");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√¬");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫Æ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‘¢");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«ﬁ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒØ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤Ï");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("π—");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âª");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡»");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’Ø");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âº");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âæ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥Á");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂‘");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À¬");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—∞");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µº");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" Ÿ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∑‚");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("…‰");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("…‰");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ω´");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œæ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œæ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("◊");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–°");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("…Ÿ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂˚");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Êÿ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º‚");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥æ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("…–");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÊŸ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥¢");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬁÃ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”»");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬁÕ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“¢");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬁŒ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æÕ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬁœ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" ¨");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“¸");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥ﬂ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÍ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒ·");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æ°");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œ≤");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œ≤");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒÚ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒÚ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æ÷");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆®");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤„");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æ”");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«¸");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÃÎ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ΩÏ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œ›");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" ∫");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆¡");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆¡");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÏ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–º");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’π");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÌ");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" Ù");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" Ù");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ¿");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¬≈");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÔ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¬ƒ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Â");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÕÕ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÕÕ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("…Ω");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“Ÿ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·®");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”Ï");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÀÍ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆Ò");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆Ò");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¨");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ß");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·©");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·™");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ø");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤Ì");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·´");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∏⁄");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·≠");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Æ");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·∞");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ∫");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·±");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·≥");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·∏");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—“");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·∂");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·µ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡Î");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·∑");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‘¿");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·≤");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·∫");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∞∂");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¥");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ø˘");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·π");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ª");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·æ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·º");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·º");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷≈");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷≈");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œø");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ω");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ω");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ø");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¬Õ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂Î");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”¯");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«Õ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∑Â");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æ˛");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¿");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¡");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·«");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥Á");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆È");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥ﬁ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—¬");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·»");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·∆");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·≈");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·√");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¬");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±¿");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’∏");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’∏");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ƒ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·À");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ã");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("· ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ô˙");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·”");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·“");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«∂");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«∂");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·…");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Œ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·–");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·‘");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·—");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Õ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·œ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·’");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·÷");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·◊");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ÿ");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·⁄");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·€");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œ°");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Á›");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥®");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷›");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—≤");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥≤");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("π§");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("◊Û");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«…");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æﬁ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("πÆ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œ◊");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤Ó");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("€œ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º∫");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“—");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À»");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∞Õ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œÔ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œÔ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ÿ„");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ΩÌ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±“");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" –");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤º");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Àß");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∑´");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" ¶");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œ£");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡¯");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’ ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡˚");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡˚");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡˙");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈¡");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ã˚");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡±");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡˘");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷„");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤Ø");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷ƒ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ€");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥¯");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷°");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œØ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∞Ô");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡¸");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡¸");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·°");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥£");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡˝");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‡˛");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√±");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√›");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¢");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∑˘");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ªœ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·£");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒª");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·§");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·•");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·¶");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥±");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥±");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∏…");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆Ω");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒÍ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤¢");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–“");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Á€");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª√");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”◊");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”ƒ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("π„");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("π„");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚œ");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("◊Ø");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«Ï");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±”");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥≤");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚—");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–Ú");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¬Æ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚–");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ø‚");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”¶");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ◊");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚“");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µÍ");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√Ì");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∏˝");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∏Æ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈”");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∑œ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚‘");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚”");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂»");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("◊˘");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ•");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚ÿ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚÷");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" ¸");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("øµ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”π");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚’");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚◊");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡Æ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¿»");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚€");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚€");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚⁄");
    rec[1] = new String("a");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¿™");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡Œ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚‹");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚›");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚ﬁ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—”");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ¢");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ω®");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÿ•");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ø™");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("€Õ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“Ï");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∆˙");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈™");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈™");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬁƒ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±◊");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬂÆ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" Ω");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬂ±");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("π≠");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“˝");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∏•");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫Î");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥⁄");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ‹");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ‹");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’≈");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√÷");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œ“");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª°");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÛ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÚ");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÙ");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ‰");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("»ı");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µØ");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µØ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«ø");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«ø");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Âˆ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ï∞");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("πÈ");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ±");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¬º");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂË");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÁ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÂÈ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“Õ");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–Œ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÕÆ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—Â");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤ ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±Î");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±Ú");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈Ì");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈Ì");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’√");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”∞");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·‹");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·›");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·›");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“€");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥π");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±À");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ˘");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’˜");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ﬁ");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("æ∂");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¥˝");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·ﬂ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫‹");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·‡");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª≤");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¬…");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("··");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–Ï");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÕΩ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·‚");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ√");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈«");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·„");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·‰");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”˘");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Â");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("—≠");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ê");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Œ¢");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("è‘");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Á");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ¬");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("·Ë");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª’");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–ƒ");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("±ÿ");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("“‰");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚·");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º…");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("»Ã");
    rec[1] = new String("r");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚„");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ï˛");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ï˝");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ﬂØ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚‚");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷æ");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Õ¸");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√¶");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„√");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("÷“");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Á");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ë");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”«");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ï");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ï");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("øÏ");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ì");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Â");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≥¿");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒÓ");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ó");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–√");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫ˆ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚È");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚È");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∑ﬁ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª≥");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ã¨");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÀÀ");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚‰");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ê");
    rec[1] = new String("o");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Í");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Î");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚˜");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ù");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‘ı");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Û");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈≠");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("’˙");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≈¬");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("≤¿");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ô");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ú");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡Ø");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Àº");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("µ°");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚˘");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("º±");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚Ò");
    rec[1] = new String("p");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–‘");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‘π");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚ı");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("π÷");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚ˆ");
    rec[1] = new String("f");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«”");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("◊‹");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì°");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚¯");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì•");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚˛");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String(" —");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("¡µ");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª–");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ø÷");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫„");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("À°");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì¶");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì£");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì¢");
    rec[1] = new String("j");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª÷");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ìß");
    rec[1] = new String("z");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–Ù");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì§");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫ﬁ");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂˜");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„°");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂≤");
    rec[1] = new String("d");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ÃÒ");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("πß");
    rec[1] = new String("g");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œ¢");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«°");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ø“");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂Ò");
    rec[1] = new String("e");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∂Ò");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚˙");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚˚");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚˝");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‚¸");
    rec[1] = new String("c");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒ’");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„¢");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”¡");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„ß");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("«ƒ");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("œ§");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„©");
    rec[1] = new String("t");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("∫∑");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„®");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ª⁄");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„£");
    rec[1] = new String("b");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„§");
    rec[1] = new String("s");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„™");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„¶");
    rec[1] = new String("k");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„¶");
    rec[1] = new String("l");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ŒÚ");
    rec[1] = new String("w");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("”∆");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ªº");
    rec[1] = new String("h");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("‘√");
    rec[1] = new String("y");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("ƒ˙");
    rec[1] = new String("n");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("Ì®");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("–¸");
    rec[1] = new String("x");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„•");
    rec[1] = new String("q");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("√ı");
    rec[1] = new String("m");
    hl.add(rec);
    rec = new Object[2];
    rec[0] = new String("„≠");
    rec[1] = new String("f");
    hl.add(rec);

  }

  /**
   * @param args
   */
  public static void main(String[] args) {
    // TODO Auto-generated method stub

  }

}
